server:
    port: 8080
eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/

spring:
 application:
  name: ApiGateWayForService
 cloud:
    gateway:
      routes:
      - id: Job_Portal_Admin
        uri: http://localhost:8082/
        predicates:
        - Path=/api/v1/**
      - id: Job_Portal_User
        uri: http://localhost:8083/
        predicates:
        - Path=/api/v1/**
          
      
  